version: "3.3"
services:
  backend:
    image: web:1.0.0
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    command: >
      sh -c "echo "======================Migrating Database==================" &&
             python manage.py migrate &&
             echo "======================Running Application=================" &&
             python manage.py runserver 0.0.0.0:8000"
